version: 2 
jobs: 
  build: 
    machine:
      docker_layer_caching: true
    
    steps:
      - checkout 
      - run:
          name: Gerando ebooks
          command: | 
              wget -O tubaina2.sh https://raw.githubusercontent.com/caelum/tubaina2/master/tubaina2.sh
              mkdir extras_env  && wget -O extras_env/01-copyright.pdf https://www.dropbox.com/s/anu5yyij7tn7pvt/01-copyright.pdf?dl=1
              if [[ $(find . -maxdepth 1 -type d -name 'book-*' | wc -l)  != "0" ]]; then
                for dir in book-*; do
                    echo "$dir"
                    if [[ -d $dir ]]; then
                      if [[ -f "$dir"/nao-buildar ]]; then
                        echo "Não vou buildar '$dir' pois tem o arquivo nao-buildar"
                        continue
                      fi
                      echo "Building $dir"
                      cp -r extras_env "$dir"
                      bash tubaina2.sh "$dir" --ebooks
                      mkdir -p "artifacts/$dir"
                      cp "$dir/.build/book.pdf" "artifacts/$dir"
                      cp "$dir/.build/book.mobi" "artifacts/$dir"
                      cp "$dir/.build/book.epub" "artifacts/$dir"
                    fi
                done
              else
                mkdir artifacts
                bash tubaina2.sh `pwd` --ebooks
                cp .build/book.pdf artifacts
                cp .build/book.mobi artifacts
                cp .build/book.epub artifacts
              fi

      - store_artifacts:
          path: artifacts
          destination: /



